### PR TITLE
Replace manual argument parsing with argparse

### PR DESCRIPTION
**Pull request by exhuma**
While investigating for OTL converters I came across this script and saw the way it handles CLI arguments.

This can be done much easier, an much more maintainable using the `argparse` module from the Python standard library. This PR converts the existing code into an argparse based implementation.

I was careful to *only* touch CLI argument processing, even including unused variables like `debug`.

### CODE REVIEW

**Comment by mcepl** [comment]
Isn't it an exact duplicate of #148? :)

**Comment by exhuma** [comment]
Oh shoot... you're right. I did not look into existing PRs... :man_facepalming:

**Comment by exhuma** [comment]
I've started a review. Unfortunately #148 breaks the script. I identified the issue and added some information. Once this is fixed I'll run it again to see if things work.

**Comment by exhuma** [comment]
Closing this as it seems to cause confusion.

**Pull request closed without merging**
